/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiAiToolRouteImport } from './routes/api/ai-tool'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as LabsIndexRouteImport } from './routes/labs/index'
import { Route as LabsProjectIdRouteImport } from './routes/labs/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiToolRoute = ApiAiToolRouteImport.update({
  id: '/api/ai-tool',
  path: '/api/ai-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsIndexRoute = LabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsProjectIdRoute = LabsProjectIdRouteImport.update({
  id: '/labs/$projectId',
  path: '/labs/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/notes': typeof NotesRoute
  '/playground': typeof PlaygroundRoute
  '/portfolio': typeof PortfolioRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/ai-tool': typeof ApiAiToolRoute
  '/api/chat': typeof ApiChatRoute
  '/labs/$projectId': typeof LabsProjectIdRoute
  '/labs/': typeof LabsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/notes': typeof NotesRoute
  '/playground': typeof PlaygroundRoute
  '/portfolio': typeof PortfolioRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/ai-tool': typeof ApiAiToolRoute
  '/api/chat': typeof ApiChatRoute
  '/labs/$projectId': typeof LabsProjectIdRoute
  '/labs': typeof LabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/notes': typeof NotesRoute
  '/playground': typeof PlaygroundRoute
  '/portfolio': typeof PortfolioRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/ai-tool': typeof ApiAiToolRoute
  '/api/chat': typeof ApiChatRoute
  '/labs/$projectId': typeof LabsProjectIdRoute
  '/labs/': typeof LabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/journal'
    | '/notes'
    | '/playground'
    | '/portfolio'
    | '/resume'
    | '/sitemap.xml'
    | '/api/ai-tool'
    | '/api/chat'
    | '/labs/$projectId'
    | '/labs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/journal'
    | '/notes'
    | '/playground'
    | '/portfolio'
    | '/resume'
    | '/sitemap.xml'
    | '/api/ai-tool'
    | '/api/chat'
    | '/labs/$projectId'
    | '/labs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/journal'
    | '/notes'
    | '/playground'
    | '/portfolio'
    | '/resume'
    | '/sitemap.xml'
    | '/api/ai-tool'
    | '/api/chat'
    | '/labs/$projectId'
    | '/labs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  JournalRoute: typeof JournalRoute
  NotesRoute: typeof NotesRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PortfolioRoute: typeof PortfolioRoute
  ResumeRoute: typeof ResumeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAiToolRoute: typeof ApiAiToolRoute
  ApiChatRoute: typeof ApiChatRoute
  LabsProjectIdRoute: typeof LabsProjectIdRoute
  LabsIndexRoute: typeof LabsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-tool': {
      id: '/api/ai-tool'
      path: '/api/ai-tool'
      fullPath: '/api/ai-tool'
      preLoaderRoute: typeof ApiAiToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/': {
      id: '/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof LabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/$projectId': {
      id: '/labs/$projectId'
      path: '/labs/$projectId'
      fullPath: '/labs/$projectId'
      preLoaderRoute: typeof LabsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  JournalRoute: JournalRoute,
  NotesRoute: NotesRoute,
  PlaygroundRoute: PlaygroundRoute,
  PortfolioRoute: PortfolioRoute,
  ResumeRoute: ResumeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAiToolRoute: ApiAiToolRoute,
  ApiChatRoute: ApiChatRoute,
  LabsProjectIdRoute: LabsProjectIdRoute,
  LabsIndexRoute: LabsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
